### PR TITLE
Style guide and validation

### PR DESCRIPTION
**Pull request by Charana123**

### CODE REVIEW

**Comment by matrixik** [comment]
Maybe it would be worth it to use something like https://prettier.io/ for code formating so that whoever develop it could use plugin to his editor that would always reformat code on save (and no more reformatting commits).

**Comment by matrixik** [comment]
Or https://github.com/sheerun/prettier-standard

**Comment by Charana123** [comment]
@matrixik Thanks for the feedback, i've added support for prettier and included it in travis :)

**Comment by matrixik** [comment]
Great.

**Pull request closed without merging**
